### ISSUE TITLE
No Resize Window

### ISSUE THREAD

**Issue by achmadsutardi441953** [1j01/os-gui#11]
i can resize window with javascript resizing a div

**Comment by 1j01** [comment]
I've now implemented window resizing (on all corners and edges), but not the bottom right resize handle which is supposed to be a  visual indication and larger hit target.

### Todo:
- [ ] special bottom right resize handle
- [ ] retro cursors for classic theme
- [ ] fix cursor flickering to other cursors from content behind while dragging (I need to make the cursor apply globally)
